export const ZTypeName = {
  Any: 'ZAny',
  Array: 'ZArray',
  BigInt: 'ZBigInt',
  Boolean: 'ZBoolean',
  Date: 'ZDate',
  Default: 'ZDefault',
  Effects: 'ZEffects',
  Enum: 'ZEnum',
  Intersection: 'ZIntersection',
  Lazy: 'ZLazy',
  Literal: 'ZLiteral',
  Map: 'ZMap',
  NaN: 'ZNaN',
  NativeEnum: 'ZNativeEnum',
  Never: 'ZNever',
  Null: 'ZNull',
  Nullable: 'ZNullable',
  Number: 'ZNumber',
  Object: 'ZObject',
  Optional: 'ZOptional',
  Promise: 'ZPromise',
  String: 'ZString',
  Symbol: 'ZSymbol',
  Tuple: 'ZTuple',
  Undefined: 'ZUndefined',
  Union: 'ZUnion',
  Unknown: 'ZUnknown',
  Void: 'ZVoid',
  ///////
  Record: 'ZRecord',
  Function: 'ZFunction',
  InstanceOf: 'ZInstanceOf',
  Set: 'ZSet',
} as const

export type ZTypeName = typeof ZTypeName[keyof typeof ZTypeName]
